### PR TITLE
fix: Resolve errors and remove incorrect parameter name insertions

### PR DESCRIPTION
**Pull request by Javakky-pxv**
Please allow me to send you a PR for the fix, as there was an error when using this rule in my repository

1. Fixed errors due to incomplete pattern matching (77c2373c1b4cd846887779aebdbfe876a38e0efb)
2. Fixed Index references beyond parameter list (91d2c15620a16fd131beee6298d8ae4c9ddd2655)
3. Resolved problem of inserting parameter names into omitted lambda arguments causing them to break (0734734cc4b0c398de9394198d10dbf050ae841f)

### CODE REVIEW

**Comment by Javakky-pxv** [comment]
The `List#apply` argument is passed as xs in scala-2.12, but is not generated in scala-2.13, so the test pattern is separated for each version.

**Comment by Javakky-pxv** [comment]
@jatcwang 
Thanks for the reaction!
Is there anything else I need to do to get this PR published?

**Comment by yarosman** [comment]
@Javakky-pxv will you release 0.2.2 version ?

**Comment by yarosman** [comment]
Mismatch)
I mean [jatcwang](https://github.com/jatcwang)

**Comment by jatcwang** [comment]
@yarosman @Javakky-pxv 0.2.2 has been released

**Pull request merged**
